Plotting the Density Variations and vertical mass flux using the mass_budget.py code
luminoctum/PolarCyclone pull request #2
Opened 2022-05-18 14:05 UTC by mayaafields

I think I have both of the plots correct. Let me know what you think.

2022-05-18 14:33 UTC, luminoctum commented on python_codes/mass_budget.py
> +mass_flux = data['v1rho'][:,:]
This is the horizontally averaged mass flux, <v1rho>

2022-05-18 14:35 UTC, luminoctum commented on python_codes/mass_budget.py
> +heat_rate= horizontally_averaged_density_var + mass_flux
I think this is incorrect.

2022-05-18 14:40 UTC, luminoctum commented on python_codes/mass_budget.py
> +contour_plot_density_var = ax.contourf(Time, Pressure,horizontally_averaged_density_var)
horizontally_average_density_var is too long. Let's name it to **rhoa_avg**
**rhoa** stands for rho - rho_0
**_avg** stands for \<\>, horizontal average

2022-05-18 14:41 UTC, luminoctum commented on python_codes/mass_budget.py
> +title(r'$\frac{\delta \rho}{\delta t}$')
You can omit the **r** in front of your string literal.

2022-05-18 14:41 UTC, luminoctum commented on python_codes/mass_budget.py
> +ax.set_xlabel(r'Time(s)',fontsize = 12)
Omit **r**

2022-05-18 14:41 UTC, luminoctum commented on python_codes/mass_budget.py
> +ax.set_ylabel(r'Pressure',fontsize = 12)
same

2022-05-18 14:42 UTC, luminoctum commented on python_codes/mass_budget.py
> +contour_plot_density_var = ax.contourf(Time, Pressure,horizontally_averaged_density_var)
simplify that line 36 to:
```
h = ax.contourf(Time, Pressure, rhop_avg)
```

2022-05-18 14:43 UTC, luminoctum commented on python_codes/mass_budget.py
> +fig.colorbar(contour_plot_mass_flux)
Then you can use
```
fig.colorbar(h)
```

2022-05-18 14:45 UTC, luminoctum commented on python_codes/mass_budget.py
> +savefig('contour_plot_heat_rate.png')
Right now, the program does not output \dot q_c. You can comment out this paragraph. We'll do the q_c part later

2022-05-18 14:46 UTC, luminoctum commented on python_codes/mass_budget.py
> +show()
How do you run this program?
```
./mass_budget.py
```
?

2022-05-18 14:55 UTC, luminoctum commented on python_codes/contour_plots.py
>  NH3_variations = NH3_total - NH3avg.reshape((1,nx1,1))
Let's formalize the naming convention. 
Temperature: **temp**
Pressure: **pres**
NH3 vapor mass mixing ratio: **qNH3v**
NH3 vapor density: **rhoNH3v**
NH3 cloud density: **rhoNH3c**
NH3 cloud mass mixing ratio: **qNH3c**
NH3 precipitation mass mixing ratio: **qNH3p**
H2O total mass mixing ratio: **qH2Ot**
temporal average: **_bar**
horizontal average: **_avg**
anomaly with respect to some reference value: **a**
so **NH3_variations** should be changed to **qNH3a**

2022-05-18 14:57 UTC, luminoctum commented on python_codes/contour_plots.py
> +NH3_variations_from_initial = NH3_total - NH3_0.reshape((1,nx1,1))
Now you have two anomalies, one from the average, another from the initial condition. Let's name them in the following way:
anomaly from average: **qNH3a1**
anomaly from the initial condition: **qNH3a2**

2022-05-18 14:57 UTC, luminoctum commented on python_codes/contour_plots.py
>  H2O_variations = H2O_total - H2Oavg.reshape((1,nx1,1))
Do the same naming for H2O

2022-05-18 14:58 UTC, luminoctum commented on python_codes/contour_plots.py
> +contour_plot_temp_var = ax.contourf(Time, Pressure, mean(temp_variations, axis =2))
rewrite that to:
```
h = ax.contourf(Time, Pressure, mean(temp_variations, axis =2))
```

2022-05-18 14:59 UTC, luminoctum commented on python_codes/contour_plots.py
>  title(r'$H_2O$ Concentration')
```
ax.set_title
```

2022-05-18 15:00 UTC, luminoctum commented on python_codes/contour_plots.py
>  fig.colorbar(contour_plot_H2O)
```
fig.colorbar(h)
```

2022-05-18 15:00 UTC, luminoctum commented on python_codes/contour_plots.py
>  fig.colorbar(contour_plot_H2O)
If you need multiple plots, use **h1**, **h2**

2022-05-18 15:01 UTC, luminoctum commented on python_codes/contour_plots.py
> +savefig('contour_plot_H2O_deep.png')
```
savefig('contour_plot_H2O_deep.png', bbox_inches = 'tight')
```

2022-05-18 15:02 UTC, luminoctum commented on python_codes/mass_budget.py
> +contour_plot_heat_rate = ax.contourf(Time, Pressure, heat_rate)
```
h = xxx
```

2022-05-18 15:02 UTC, luminoctum commented on python_codes/mass_budget.py
> +title(r'$-<\rho \dot{q_c}>$')
set_title

2022-05-18 15:02 UTC, luminoctum commented on python_codes/contour_plots.py
>  fig.colorbar(contour_plot_temp_var)
fig.colorbar(h)

2022-05-18 15:03 UTC, luminoctum commented on python_codes/contour_plots.py
> +savefig('contour_plot_temp_deep.png')
```
savefig('xxx', bbox_inches = 'tight')
```

2022-05-18 15:04 UTC, luminoctum commented on python_codes/contour_plots.py
> +contour_plot_H2O = ax.contourf(Time, Pressure, sum(H2O_variations_from_initial, axis = 2))
Normally, we use lower case words for a variable. so change Time to **time**, Pressure to **pres**

2022-05-18 15:05 UTC, luminoctum requested changes
Let me know how your run these two programs. I'll set up continuous integration.

2022-05-24 16:37 UTC, mayaafields commented
![contour_plot_density](https://user-images.githubusercontent.com/47670713/170087631-253129bd-86ad-4a2e-8dc0-d13ab59f0c86.png)

2022-05-24 21:32 UTC, luminoctum approved these changes

2022-05-24 21:33 UTC, luminoctum commented
I'll merge the request. We can discuss the figure later.

2022-05-24 21:33 UTC, merged